/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devilwwj_jni_TestJNI */

#ifndef _Included_com_devilwwj_jni_TestJNI
#define _Included_com_devilwwj_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devilwwj_jni_TestJNI
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_devilwwj_jni_TestJNI_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_devilwwj_jni_TestJNI
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_devilwwj_jni_TestJNI_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_devilwwj_jni_TestJNI
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_devilwwj_jni_TestJNI_destory
  (JNIEnv *, jobject);

/*
 * Class:     com_devilwwj_jni_TestJNI
 * Method:    createANativeCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_devilwwj_jni_TestJNI_createANativeCrash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
